apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: everything-pipeline
  namespace: devsecops
spec:
  params:
  - name: git-repo-url
  - name: git-repo-ssh-url
  - name: git-repo-event-target-ref
  - name: pipelinerun-name
  - name: pullreq-sha
  - name: pullreq-ref
  - name: pullreq-action
  - name: pullreq-number
  - name: pullreq-repo-full_name
  - name: pullreq-html-url
  - name: pullreq-title
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.pipelinerun-name)-
    spec:
      params:
        - name: verbose
          value: "true"
        - name: appRepoUrl
          value: $(tt.params.git-repo-url)
        - name: appRepoRef
          value: $(tt.params.git-repo-event-target-ref)
        - name: stepRunnerConfigDir
          value: /opt/platform-config/ /opt/platform-config-secrets/ cicd/ploigos-software-factory-operator/ploigos-step-runner-config/
        - name: pgpKeysSecretName
          value: ploigos-gpg-key
        - name: stepRunnerPackageName
          value: ploigos-step-runner
        - name: stepRunnerUpdateLibrary
          value: "false"
        - name: stepRunnerLibIndexUrl
          value: https://pypi.org/simple/
        - name: stepRunnerLibExtraIndexUrl
          value: https://pypi.org/simple/
        - name: envNameDev
          value: DEV
        - name: envNameTest
          value: TEST
        - name: envNameProd
          value: PROD
        - name: ciOnlyGitRefPatterns
          value: ^$
        - name: devGitRefPatterns
          value: ^feature/.+$|^PR-.+$
        - name: releaseGitRefPatterns
          value: ^main$
        - name: workflowWorkerImageDefault
          value: quay.io/ploigos/ploigos-tool-maven:latest
        - name: workflowWorkerImageSourceClone
          value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.12.1
        - name: workflowWorkerImageUnitTest
          value: quay.io/ploigos/ploigos-tool-maven:latest
        - name: workflowWorkerImagePackage
          value: quay.io/ploigos/ploigos-tool-maven:latest
        - name: workflowWorkerImageStaticCodeAnalysis
          value: quay.io/ploigos/ploigos-tool-sonar:latest
        - name: workflowWorkerImagePushArtifacts
          value: quay.io/ploigos/ploigos-tool-maven:latest
        - name: workflowWorkerImageContainerOperations
          value: ploigos/ploigos-tool-containers:latest
        - name: workflowWorkerImageContainerImageStaticComplianceScan
          value: ploigos/ploigos-tool-openscap:latest
        - name: workflowWorkerImageContainerImageStaticVulnerabilityScan
          value: ploigos/ploigos-tool-openscap:latest
        - name: workflowWorkerImageDeploy
          value: ploigos/ploigos-tool-argocd:latest
        - name: workflowWorkerImageValidateEnvironmentConfiguration
          value: ploigos/ploigos-tool-config-lint:latest
        - name: workflowWorkerImageUAT
          value: quay.io/ploigos/ploigos-tool-maven:latest
        - name: workflowWorkerImageAutoGov
          value: ploigos/ploigos-tool-autogov:latest
      pipelineRef:
        name: app1-service1
      resources: [ ]
      serviceAccountName: pipeline
      workspaces:
        - name: home
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
        - name: app
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - configMap:
            name: ploigos-platform-config-demo
          name: ploigos-platform-config
        - name: ploigos-platform-config-secrets
          secret:
            secretName: ploigos-platform-config-secrets-demo
